version: '3.7'

services:
  # client:
  #   build:
  #     context: .
  #     dockerfile: ./Container/Frontend/Dockerfile
  #   image: itree_front/react:v1
  #   volumes:
  #     - ./volumes/Frontend:/Frontend
  #   ports:
  #     - '3000:3000'
  #   restart: unless-stopped
  #   networks:
  #     - webappnetwork
  api:
    build:
      context: .
      dockerfile: ./Container/Backend/Dockerfile
    image: backend
    volumes:
      # - ./volumes/uploads:/api/uploads
      - type: bind
        source: ./Backend
        target: /api
    ports:
      - '5000:3000'
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
    image: mongo
    volumes:
      - ./volumes/data/db:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - webappnetwork

networks:
    webappnetwork:
        driver: bridge
        
volumes:
  data:
