version: "3"

services:
  strapi:
    image: naskio/strapi
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV : ${NODE_ENV}
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"


